# Generated by Django 4.1 on 2022-09-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updateorder',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('update_desc', models.CharField(default='', max_length=503)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
